### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by bsedg** [bsedg/irest#23]
Complete test coverage is still a work in progress, so this issue is aimed at having 100% test coverage for `test.go`.

Status of coverage as of 354bdef8613838fac272a2b5d0d7fa9ec8f45c68 on `development`:

- [x] github.com/bsedg/irest/test.go:38:	NewTest				100.0%
- [x] github.com/bsedg/irest/test.go:55:	NewTest				100.0%
- [x] github.com/bsedg/irest/test.go:75:	AddHeader			100.0%
- [ ] github.com/bsedg/irest/test.go:81:	AddCookie			0.0%
- [x] github.com/bsedg/irest/test.go:87:	Get				100.0%
- [x] github.com/bsedg/irest/test.go:93:	Post				100.0%
- [ ] github.com/bsedg/irest/test.go:99:	Put				0.0%
- [ ] github.com/bsedg/irest/test.go:104:	Delete				0.0%
- [ ] github.com/bsedg/irest/test.go:108:	do				63.0%
- [ ] github.com/bsedg/irest/test.go:154:	ParseResponseBody		50.0%
- [ ] github.com/bsedg/irest/test.go:179:	MustStatus			60.0%
- [ ] github.com/bsedg/irest/test.go:193:	MustStringValue			60.0%
- [ ] github.com/bsedg/irest/test.go:206:	MustIntValue			0.0%
- [ ] github.com/bsedg/irest/test.go:224:	Must				80.0%
- [ ] github.com/bsedg/irest/test.go:238:	SaveCookie			58.3%
- [ ] total:					(statements)			43.1%

**Comment by stangles** [comment]
I'd like to claim this, @bsedg.

**Comment by bsedg** [comment]
Go ahead @stangles all yours if you want it

**Comment by stangles** [comment]
Opened #28 for this.

**Comment by bsedg** [comment]
fixed with #28
